name: basic-system-monitor
version: '0.1'
summary: A basic system monitor in Go
description: |
  A terminal-based system monitor written in Go, displaying CPU, RAM, disk,
  and network usage, along with a sortable process list.

grade: devel # Can be 'stable' or 'devel'
confinement: strict # Use 'strict' for production snaps

base: core22 # Use the latest base snap

parts:
  basic-system-monitor:
    plugin: go
    source: .
    build-packages:
      - git
    override-build: |
      go mod download
      go build -o basic-system-monitor -v ./...

apps:
  basic-system-monitor:
    command: basic-system-monitor
    plugs:
      - network
      - network-bind
      - system-observe
      - home # For config.yaml and general user files
